/**
 * Supported GirderCore environments.
 */
export type GirderCoreEnvironment = 'sandbox' | 'production';

/**
 * Configuration options for the GirderCore client.
 */
export interface ClientConfig {
  /** API key used for Bearer token authentication. */
  apiKey: string;
  /** Target environment. */
  environment: GirderCoreEnvironment;
}

/**
 * Payment status values.
 */
export type PaymentStatus = string;

/**
 * Order details for initiating a payment.
 */
export interface Order {
  /** Unique identifier for the client initiating the order. */
  clientUid: string;
  /** Integration key associated with the merchant/integration. */
  integrationKey: string;
  /** Amount to be charged. */
  amount: number;
  /** ISO 4217 currency code (e.g., "USD"). */
  currency: string;
  /** Optional reason or description for the payment. */
  reason?: string;
}

/**
 * Customer information for initiating a payment.
 */
export interface Customer {
  /** Full name of the customer. */
  names: string;
  /** Email address of the customer. */
  email: string;
  /** Mobile phone number in E.164 format. */
  msisdn: string;
  /** Optional language code (e.g., "en"). */
  language?: string;
}

/**
 * Payload for the Init Payment endpoint.
 */
export interface InitPaymentRequest {
  /** Code of the payment provider to use (e.g., "PROXYPAY_CD"). */
  providerCode: string;
  /** Order details. */
  order: Order;
  /** Customer details. */
  customer: Customer;
}

/**
 * Response from the Init Payment endpoint.
 */
export interface InitPaymentResponse {
  /** Unique transaction identifier generated by GirderCore. */
  transactionUid: string;
  /** Current status of the newly created payment. */
  status: PaymentStatus;
}

/**
 * Payload for the Submit Payment Method endpoint.
 */
export interface SubmitPaymentMethodRequest {
  /** Name of the payment method (e.g., "MOBILEMONEY"). */
  name: string;
  /** Mobile phone number / wallet ID associated with the method. */
  msisdn: string;
  /** Provider code (e.g., "MPESA"). */
  provider: string;
}

/**
 * Order snapshot returned in payment status responses.
 */
export interface PaymentOrderSnapshot {
  currency: string;
  amount: number;
  customerFullName: string;
  customerEmailAddress: string;
}

/**
 * Payment channel details.
 */
export interface PaymentChannel {
  channel: string;
  provider: string;
  walletId: string;
}

/**
 * Request snapshot returned in payment status responses.
 */
export interface PaymentRequestSnapshot {
  order: PaymentOrderSnapshot;
  paymentChannel: PaymentChannel;
}

/**
 * Generic payment status response.
 */
export interface PaymentStatusResponse {
  /** Snapshot of the original request. */
  request: PaymentRequestSnapshot;
  /** Client unique identifier. */
  clientUid: string;
  /** Current status of the payment. */
  status: PaymentStatus;
  /** Optional error message if the transaction failed. */
  error?: string;
}

// ---------------------------------------------------------------------------
// Deprecated aliases — kept for backward compatibility
// ---------------------------------------------------------------------------

/** @deprecated Use {@link PaymentOrderSnapshot} instead. */
export interface ProxyPayOrder extends PaymentOrderSnapshot {}

/** @deprecated Use {@link PaymentChannel} instead. */
export interface ProxyPayPaymentChannel extends PaymentChannel {}

/** @deprecated Use {@link PaymentRequestSnapshot} instead. */
export interface ProxyPayRequest extends PaymentRequestSnapshot {}

/** @deprecated Use {@link PaymentStatusResponse} instead. */
export interface ProxyPayPaymentStatusResponse extends PaymentStatusResponse {}

// ---------------------------------------------------------------------------
// Find payment response
// ---------------------------------------------------------------------------

/**
 * Generic payment object returned when finding a payment by reference.
 *
 * Note: The exact shape may vary depending on the provider and payment state.
 */
export interface FindPaymentResponse {
  /** Unique transaction identifier. */
  transactionUid?: string;
  /** Current status of the payment. */
  status?: PaymentStatus;
  /** Order details. */
  order?: Order;
  /** Customer details. */
  customer?: Customer;
  /** Payment channel details, if already submitted. */
  paymentChannel?: PaymentChannel;
  /** Error message, if any. */
  error?: string;
  /** Additional provider-specific metadata. */
  metadata?: Record<string, unknown>;
  [key: string]: unknown;
}
